"""
SQLAlchemy ORM models.
- Document: PDF metadata (vectors live in FAISS, see rag/vectorstore.py).
- Conversation: A named chat session belonging to one user.
- Message: An individual turn (user or assistant) inside a conversation.
"""
import uuid
from datetime import datetime, timezone
from sqlalchemy import String, Integer, DateTime, Text, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.database import Base


def _uuid() -> str:
    return uuid.uuid4().hex[:12]


class Document(Base):
    __tablename__ = "documents"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    filename: Mapped[str] = mapped_column(String, nullable=False)
    stored_path: Mapped[str] = mapped_column(String, nullable=False)
    size_kb: Mapped[int] = mapped_column(Integer, default=0)
    chunks_indexed: Mapped[int] = mapped_column(Integer, default=0)
    status: Mapped[str] = mapped_column(String, default="indexing")  # indexing | ready | failed
    uploaded_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc)
    )

    # RBAC metadata — used to filter documents per user role
    department: Mapped[str] = mapped_column(String, default="General")
    access_level: Mapped[str] = mapped_column(String, default="public")  # public | internal | confidential
    # Comma-separated roles that may access this document, e.g. "admin,hr,finance"
    allowed_roles: Mapped[str] = mapped_column(String, default="admin,employee")

    # Admin-reviewed summary generated by Groq at upload time
    summary: Mapped[str] = mapped_column(String, default="")


class Conversation(Base):
    """
    A chat session owned by a single user.
    user_id matches the hardcoded id values in the frontend AuthContext
    (u1=admin, u3=bob/hr, u4=carol/finance, u5=dave/it).
    """
    __tablename__ = "conversations"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(String, nullable=False, index=True)
    # Short title auto-generated from the first user question
    title: Mapped[str] = mapped_column(String, default="New Conversation")
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    messages: Mapped[list["Message"]] = relationship(
        "Message", back_populates="conversation",
        order_by="Message.created_at",
        cascade="all, delete-orphan",
    )


class Message(Base):
    """
    A single turn in a conversation.
    role: 'user' | 'assistant'
    sources_json: JSON-encoded list of RetrievedChunk dicts (assistant only).
    """
    __tablename__ = "messages"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    conversation_id: Mapped[str] = mapped_column(
        String, ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    role: Mapped[str] = mapped_column(String, nullable=False)       # 'user' | 'assistant'
    content: Mapped[str] = mapped_column(Text, nullable=False)
    # Primary source filename for assistant messages (e.g. "TechNova_HR_Policy.pdf")
    source: Mapped[str] = mapped_column(String, default="")
    # JSON array of RetrievedChunk objects so citations can be re-rendered on reload
    sources_json: Mapped[str] = mapped_column(Text, default="[]")
    # True when the assistant response is an error / access-restricted notice
    is_error: Mapped[bool] = mapped_column(Integer, default=False)
    error_code: Mapped[str] = mapped_column(String, default="")
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc)
    )

    conversation: Mapped["Conversation"] = relationship("Conversation", back_populates="messages")
