"""
SQLAlchemy ORM models.
- Document:     PDF metadata (vectors live in FAISS, see rag/vectorstore.py).
- Conversation: A named chat session belonging to one user.
- Message:      An individual turn (user or assistant) inside a conversation.
- AuditEvent:   Immutable append-only audit log for the monitoring dashboard.
"""
import uuid
from datetime import datetime, timezone
from sqlalchemy import String, Integer, DateTime, Text, ForeignKey, UniqueConstraint, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.database import Base


def _uuid() -> str:
    return uuid.uuid4().hex[:12]


class Document(Base):
    __tablename__ = "documents"
    # Database-level uniqueness on the SHA-256 content hash.
    # This is the last line of defence against race-condition duplicates:
    # even if two identical uploads arrive simultaneously and both pass the
    # application-layer check, the DB will reject the second INSERT.
    __table_args__ = (
        UniqueConstraint("sha256_hash", name="uq_documents_sha256_hash"),
    )

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    filename: Mapped[str] = mapped_column(String, nullable=False)
    stored_path: Mapped[str] = mapped_column(String, nullable=False)
    size_kb: Mapped[int] = mapped_column(Integer, default=0)
    chunks_indexed: Mapped[int] = mapped_column(Integer, default=0)
    status: Mapped[str] = mapped_column(String, default="indexing")  # indexing | ready | failed
    uploaded_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc)
    )

    # SHA-256 hex digest of the raw PDF bytes.
    # Used for exact-duplicate detection; NOT derived from the filename.
    sha256_hash: Mapped[str] = mapped_column(String(64), nullable=False, index=True)

    # RBAC metadata — used to filter documents per user role
    department: Mapped[str] = mapped_column(String, default="General")
    access_level: Mapped[str] = mapped_column(String, default="public")  # public | internal | confidential
    # Comma-separated roles that may access this document, e.g. "admin,hr,finance"
    allowed_roles: Mapped[str] = mapped_column(String, default="admin,employee")

    # Admin-reviewed summary generated by Groq at upload time
    summary: Mapped[str] = mapped_column(String, default="")


class Conversation(Base):
    """
    A chat session owned by a single user.
    user_id matches the hardcoded id values in the frontend AuthContext
    (u1=admin, u3=bob/hr, u4=carol/finance, u5=dave/it).
    """
    __tablename__ = "conversations"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(String, nullable=False, index=True)
    # Short title auto-generated from the first user question
    title: Mapped[str] = mapped_column(String, default="New Conversation")
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    messages: Mapped[list["Message"]] = relationship(
        "Message", back_populates="conversation",
        order_by="Message.created_at",
        cascade="all, delete-orphan",
    )


class Message(Base):
    """
    A single turn in a conversation.
    role: 'user' | 'assistant'
    sources_json: JSON-encoded list of RetrievedChunk dicts (assistant only).
    """
    __tablename__ = "messages"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    conversation_id: Mapped[str] = mapped_column(
        String, ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    role: Mapped[str] = mapped_column(String, nullable=False)       # 'user' | 'assistant'
    content: Mapped[str] = mapped_column(Text, nullable=False)
    # Primary source filename for assistant messages (e.g. "TechNova_HR_Policy.pdf")
    source: Mapped[str] = mapped_column(String, default="")
    # JSON array of RetrievedChunk objects so citations can be re-rendered on reload
    sources_json: Mapped[str] = mapped_column(Text, default="[]")
    # True when the assistant response is an error / access-restricted notice
    is_error: Mapped[bool] = mapped_column(Integer, default=False)
    error_code: Mapped[str] = mapped_column(String, default="")
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc)
    )

    conversation: Mapped["Conversation"] = relationship("Conversation", back_populates="messages")


class AuditEvent(Base):
    """
    Append-only audit / activity log.

    Every significant action in the system writes one row here:
    queries, RBAC denials, document uploads/deletes, access changes,
    guardrail blocks, and admin actions.

    Event type taxonomy (stored in event_type column):
      Query Activity   : QUERY_SUCCESS | QUERY_FAILED | QUERY_NO_DOCS
      Security Events  : RBAC_DENIED | UNAUTH_ACCESS | PROMPT_INJECTION
                         OUT_OF_SCOPE | GUARDRAIL_BLOCKED
      Document Activity: DOC_UPLOADED | DOC_DUPLICATE | DOC_DELETED
                         DOC_ACCESS_CHANGED | SUMMARY_GENERATED
      System           : LOGIN_FAILED (reserved for future)

    Result taxonomy (stored in result column):
      success | denied | blocked | failed | info

    Design notes:
    - Rows are never mutated or deleted (append-only audit trail).
    - Sensitive document content is never stored; only IDs, filenames,
      and metadata are recorded.
    - Composite indexes cover the three most common filter axes:
      (timestamp DESC), (user_id, timestamp), (event_type, timestamp).
    """
    __tablename__ = "audit_events"
    __table_args__ = (
        # Fast descending time-range queries (default dashboard view)
        Index("ix_audit_events_timestamp", "timestamp"),
        # Filter by user across time
        Index("ix_audit_events_user_id_timestamp", "user_id", "timestamp"),
        # Filter by event type across time
        Index("ix_audit_events_event_type_timestamp", "event_type", "timestamp"),
        # Filter by result (success/denied/blocked/failed)
        Index("ix_audit_events_result", "result"),
    )

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)

    # When — stored as UTC, always set at insert time
    timestamp: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=lambda: datetime.now(timezone.utc)
    )

    # Who — user identifiers from request headers (may be empty for unauthenticated)
    user_id: Mapped[str] = mapped_column(String, default="")
    user_name: Mapped[str] = mapped_column(String, default="")
    user_role: Mapped[str] = mapped_column(String, default="")

    # What happened
    event_type: Mapped[str] = mapped_column(String, nullable=False)  # see taxonomy above
    action: Mapped[str] = mapped_column(String, default="")          # human-readable label
    result: Mapped[str] = mapped_column(
        String, nullable=False, default="info"
    )  # success | denied | blocked | failed | info

    # Document context (filled only for document-related events)
    document_id: Mapped[str] = mapped_column(String, default="")
    document_name: Mapped[str] = mapped_column(String, default="")

    # Extra detail — short free-text, no document content
    detail: Mapped[str] = mapped_column(Text, default="")
